### PR TITLE
Support for Wagtail 2

### PR DESCRIPTION
**Pull request by po5i**
This PR let this library support for Wagtail 2.

Tested on Wagtail 2.1

### CODE REVIEW

**Comment by alexgleason** [comment]
Bump - this is needed for a client. :slightly_smiling_face: Thanks for your work on this.

**Comment by alexgleason** [comment]
I've actually just tested this and got the following error when trying to view the link checker page: http://dpaste.com/0P934YS

I have defined `DEFAULT_PER_PAGE = 50` in my settings file.

**Comment by alexgleason** [comment]
Sorry for the triple post. It's because `from django.conf import settings` is missing from the top of `views.py`.

The crash happens here:

https://github.com/takeflight/wagtail-linkchecker/blob/7a36fcb9d2f97e8b62472d93204dc7251dcde956/wagtaillinkchecker/views.py#L47

Because strangely there's a view-function in the file called `settings`.

https://github.com/takeflight/wagtail-linkchecker/blob/7a36fcb9d2f97e8b62472d93204dc7251dcde956/wagtaillinkchecker/views.py#L70-L75

Not the crash I was expecting. Might be worth changing the view function to something like `linkchecker_settings` just in case?

**Comment by po5i** [comment]
Hey @alexgleason thanks for checking this.

I just fixed by adding the `import` inside the `index` view. I'd prefer not change the `settings` view name for now.

If you're interested I also have a branch that used `django-rq` instead of `celery`.

**Comment by alexgleason** [comment]
Hi @po5i, thank you for updating it! I gave it a try, and while it does seem to be working, after I click the "Scan" button it redirects me to this error:

>**DataError at /admin/link-checker/scan/**
>value too long for type character varying(200)

Full traceback: http://dpaste.com/2B69HRS

It looks like you changed `models.py` but did not include a migration file; I'm wondering if this is the cause of it.

Backing out to `/admin/link-checker/`, I can see the completed scans as well as their individual detail views. I'm not sure if the scans are actually completing. This problem only happens when clicking "Scan" - I'm redirected to the error page after a minute or so.

**Comment by po5i** [comment]
My bad, I forgot to include the file. It's pushed now.

Thanks!

**Comment by alexgleason** [comment]
@SableWalnut This version is 100% working for me now. I'm using it in production, pointing to Carlos's git branch.

Any chance you're willing to merge/deploy to PyPi? If you're busy you're also welcome add me as a collaborator here (also `alexgleason` on PyPi) and I can help maintain the package.

**Comment by po5i** [comment]
Same here! using it at production right now (but with `django-rq` instead of `celery`)

**Comment by po5i** [comment]
Hey @SableWalnut can you take a look at this?

**Comment by seb-b** [comment]
Hi @po5i, thanks for this pr, sorry about the delay.

For the discussion around the `DEFAULT_PER_PAGE` setting, this is a default setting we have in our projects here at Takeflight so I assume it's a hangover from that.
I'll ditch it and make the value static before release, less config the better :)

**Pull request merged**
